version: "3.8"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    # command: ["redis-server"] --> for run container with custom params
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis_data:/data
    networks:
      - compose-net
    restart: unless-stopped
  tracking-notification-js-container:
    image: maur025/tracking-notification-js:0.0.3
    container_name: tracking-notification-js-container
    hostname: tracking-notification-js-container
    ports:
      - "8801:8801"
    env_file:
      - ./.env
    volumes:
      # - notification_data:/app/database
      - ./database:/app/database
    networks:
      - compose-net
    depends_on:
      - redis

volumes:
  redis_data:
  notification_data:

networks:
  compose-net:
    driver: bridge