const {
	APP_PORT = 7768,
	APP_STATIC_PUBLIC_PATH = "./public",

	REDIS_HOST = "localhost",
	REDIS_PORT = "6379",

	WHATSAPP_BROWSER_LIFETIME_MINUTES = "10",
	WHATSAPP_BROWSER_VERIFY_LIFE_MINUTES = "5",

	WS_GATEWAY_HOST_PROCESSOR = "localhost",
	WS_GATEWAY_PORT_PROCESSOR = "7160",
} = process.env;

export const environments = {
	APP_PORT: Number(APP_PORT),
	APP_STATIC_PUBLIC_PATH,
	REDIS_HOST,
	REDIS_PORT: Number(REDIS_PORT),
	WHATSAPP_BROWSER_LIFETIME_MINUTES: Number(WHATSAPP_BROWSER_LIFETIME_MINUTES),
	WHATSAPP_BROWSER_VERIFY_LIFE_MINUTES: Number(WHATSAPP_BROWSER_VERIFY_LIFE_MINUTES),
	WS_GATEWAY_HOST_PROCESSOR,
	WS_GATEWAY_PORT_PROCESSOR: Number(WS_GATEWAY_PORT_PROCESSOR),
};
