name: CI notification

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  review-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      # - name: config github http access
      #   run: |
      #     git config --global url."https://x-access-token:${{ secrets.TRACKING_COMMON_ACCESS }}@github.com/".insteadOf "git@github.com:"
      #     git config --global url."https://x-access-token:${{ secrets.TRACKING_COMMON_ACCESS }}@github.com/".insteadOf "git+ssh://git@github.com:"
      #     git config --global url."https://x-access-token:${{ secrets.TRACKING_COMMON_ACCESS }}@github.com/".insteadOf "ssh://git@github.com:"

      - name: update tracking-common dependency
        env:
          TRACKING_COMMON_ACCESS: ${{ secrets.TRACKING_COMMON_ACCESS }}
        run: sed -i "s|\"file:../tracking-common\"|\"git+https://x-access-token:${TRACKING_COMMON_ACCESS}://@github.com/Maur025/tracking-common.git\"|g" package.json

      - name: Update tracking-common dependency in pnpm-lock.yaml
        run: pnpm install --lockfile-only

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Syntax check
        run: pnpm lint
        continue-on-error: false

      - name: Run unit tests
        run: pnpm test